---
- name: Check if automysqlbackup is installed
  command:  bash -c "dpkg --get-selections | grep automysqlbackup"
  ignore_errors: True
  register: automysqlbackup_installed
  tags:
    - install_automysqlbackup

- name: Install automysqlbackup
  apt: name=automysqlbackup state=present
  when: automysqlbackup_installed | failed
  tags:
    - install_automysqlbackup

# Change the default CREATE_DATABASE option to NO so the backup file can be used in any database
- name: Edit automysqlbackup configuration
  lineinfile:
    dest: /etc/default/automysqlbackup
    state: present
    regexp: "^CREATE_DATABASE=yes$"
    line: "CREATE_DATABASE=no"
    backrefs: yes
  tags:
    - install_automysqlbackup

# Ubuntu installs a cron script with this program that will run it every day.
# It will organize the files to the appropriate directory.
- name: Run backup command
  command: automysqlbackup
  tags:
    - backup_cmd
