---
- hosts: nagiosserver
  user: "{{ host_user }}"
  become: yes
  become_method: sudo
  vars:
    nagcmd_group: nagcmd
    nagios_group: nagios
    nagios_user: nagios
    nagiosadmin_user: nagiosadmin
  vars_files:
    - vars.yml
    - secret_vars.yml
  roles:
    - lamp_stack
    - nagios_server
    - add_host_to_nagios_server
