---
- hosts: all
  user: "{{ host_user }}"
  become: yes
  become_method: sudo
  vars:
    nagcmd_group: nagcmd
    nagios_group: nagios
    nagios_user: nagios
  vars_files:
    - vars.yml
  roles:
    - lamp_stack
    - nagios
