---
# Playbook to set up new relic for monitoring a nodejs application on AWS
# This assumes node js and npm are already installed on the host
# Add require('newrelic'); as the first line of your app's main module after running this playbook.
- hosts: nagioshost
  remote_user: "{{ host_user }}"
  become: yes
  become_method: sudo
  vars_files:
    - vars.yml
    - secret_vars.yml
  roles:
    - new_relic
