---
- name: Download precompiled Vault binary and Consul
  get_url:
    url: "{{ item }}"
    dest: /usr/local/bin
  with_items:
    - https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip
    - https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
  register: zipped_file
  tags:
    - install_vault_and_consul

### TO DO::: Figure out how to make this Unzip part indempotent
- name: Unzip Vault binary and Consul
  unarchive:
    src: "{{ item.dest }}"
    dest: /usr/local/bin
    copy: no
  with_items:
    - "{{ zipped_file.results }}"
  when: zipped_file | changed
  tags:
    - install_vault_and_consul
