---
- name: Update apt cache
  apt: update_cache=yes

- name: Install python-mysqldb
  apt: name=python-mysqldb state=present

- name: Install mysql-utilities
  apt: name=mysql-utilities state=present
