---
- name: Update apt cache
  apt: update_cache=yes

- name: Install git
  apt: name=git state=present

- name: Install unzip
  apt: name=unzip state=present

- name: Copy fake aws credentials
  copy:
    src: files/credentials
    dest: "{{ ansible_env.PWD }}/.aws/credentials"
