---
- name: Create mean app directory
  file: path="/home/{{ host_user }}/app" state=directory

- name: Clone node app repository
  git:
    repo: "{{ node_app_repo }}"
    dest: "/home/{{ host_user }}/app"

- name: Install node js packages
  npm: path="/home/{{ host_user }}/app"

- name: Install Forever
  npm: name=forever global=yes

- name: Launch application continuously
  command: forever start server.js
  args:
    chdir: "/home/{{ host_user }}/app"
