- name: Convert cloudformation template from j2 to json
  local_action: template src={{ cloudformation_template }}.j2 dest={{ cloudformation_template }}

# Launch cloudformation template to create a VPC with a private & public subnet
- name: Launch ansible cloudformation template
  cloudformation:
    stack_name: "{{ cloudformation_stack_name }}"
    state: "present"
    region: "{{ region }}"
    disable_rollback: true
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    template: "{{ cloudformation_template }}"
    tags:
      Stack: "VPC-ansible-cloudformation"
