---
# tasks file to set up awscli

# - name: pip install awscli
#   pip:
#     name: awscli
#     state: latest

- name: enable tab completion for awscli
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    line: "complete -C aws_completer aws"
    state: present

- name: create .aws dir under user home for awscli config
  file:
    path: "{{ ansible_env.HOME }}/.aws"
    state: directory
    owner: "{{ ANSIBLE_USER }}"
    mode: 0755

# put together a config file for awscli using templates
- name: copy awscli config using templates
  template:
    src: awscli_config.j2
    dest: "{{ ansible_env.HOME }}/.aws/config"
    owner: "{{ ANSIBLE_USER }}"
    mode: 0644
