---
- name: Check if apache is installed
  command: bash -c "dpkg --get-selections | grep apache2"
  register: apache_installed
  ignore_errors: True
  tags:
    - apache_setup

- name: Install apache
  apt: name=apache2 state=present
  when: apache_installed|failed
  tags:
    - apache_setup

- name: Check if mysql is installed
  command: bash -c "dpkg --get-selections | grep {{ item }}"
  register: mysql_installed
  ignore_errors: True
  with_items:
    - mysql-server
    - php5-mysql
  tags:
    - mysql_setup

- name: Install mysql
  apt: name={{ item }} state=present
  when: mysql_installed|failed
  with_items:
    - mysql-server
    - php5-mysql
  tags:
    - mysql_setup

- name: Check if php is installed
  command: bash -c "dpkg --get-selections | grep {{ item }}"
  register: php_installed
  ignore_errors: True
  with_items:
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
  tags:
    - php_setup

- name: Install php
  apt: name={{ item }} state=present
  when: php_installed|failed
  with_items:
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
  tags:
    - php_setup
