---
- name: Terminate an ec2 instance
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: "absent"
    instance_ids: "{{ ec2_instance_id }}"
    region: "{{ region }}"

- name: Deregister AMI (delete associated snapshots)
  ec2_ami:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    image_id: "{{ ami_id }}"
    delete_snapshot: True
    state: absent
