---
- name: Terminate an ec2 instance
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: "absent"
    instance_ids: "{{ ec2_instance_id }}"
    region: "{{ region }}"
