---
- name: Create an empty S3 bucket
  s3:
    bucket: "{{ BUCKET_NAME }}"
    mode: create
    permission: public-read
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"

- name: Encrypt S3 bucket
  s3_bucket:
    name: "{{ BUCKET_NAME }}"
    policy: "{{ lookup('file','policy.json') }}"
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"

- name: Upload files to S3 bucket
  s3:
    bucket: "{{ BUCKET_NAME }}"
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    object: "{{ item.object }}"
    src: "{{ item.src }}"
    mode: put
    permission: public-read
  with_items:
    - { object: index.html, src: files/index.html }
    - { object: error.html, src: files/error.html }

- name: Configure bucket as static website
  command: "aws s3 website s3://{{ BUCKET_NAME }}/ --index-document index.html --error-document error.html"
