- name: Remove cloudformation stack
  cloudformation:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    stack_name: "{{ cloudformation_stack_name }}"
    region: "{{ ec2_region }}"
    state: absent
