---

- name: Copy backup script to server
  template: src=backup.sh.j2 dest=/etc/automysqlbackup/backup.sh mode=0755
  tags:
    - copy_backup_script

- name: Cron job to verify backup and upload to S3
  cron:
    name: "verify automysqlbackup and copy to S3"
    special_time: daily
    job: "/etc/automysqlbackup/backup.sh"
  tags:
    - run_cron
