---

- name: Copy backup script to server
  template: src=backup.sh.j2 dest="{{ansible_env.PWD}}/backup.sh" mode=0755
  tags:
    - copy_backup_script

- name: Cron job to verify backup and upload to S3
  cron:
    name: "verify automysqlbackup and copy to S3"
    special_time: daily
    job: "{{ansible_env.PWD}}/backup.sh"
    state: present
  tags:
    - run_cron
