- name: Install newrelic
  npm: name=newrelic path="/home/{{ host_user }}/{{ app_folder }}"
  tags:
    - newrelic_install

- name: Copy newrelic file
  template:
    src: newrelic.js.j2
    dest: "/home/{{ host_user }}/{{ app_folder }}/newrelic.js"
    force: no
  tags:
    - newrelic_file
